AddTextEntry("WEAPON_M9_AUTOTRONIC", "M9 Bayonet Autotronic")
AddTextEntry("WEAPON_M9_BLACKLAMINATE", "M9 Bayonet Black Laminate")
AddTextEntry("WEAPON_M9_BLUESTEEL", "M9 Bayonet Blue Steel")
AddTextEntry("WEAPON_M9_BRIGHTWATER", "M9 Bayonet Bright Water")
AddTextEntry("WEAPON_M9_CASEHARDENED", "M9 Bayonet Case Hardened")
AddTextEntry("WEAPON_M9_CRIMSONWEB", "M9 Bayonet Crimson Web")
AddTextEntry("WEAPON_M9_DAMASCUSSTEEL", "M9 Bayonet Damascus Steel")
AddTextEntry("WEAPON_M9_DOPPLERBLACKPEARL", "M9 Bayonet Doppler Black Pearl")
AddTextEntry("WEAPON_M9_DOPPLERP1", "M9 Bayonet Doppler Phase 1")
AddTextEntry("WEAPON_M9_DOPPLERP2", "M9 Bayonet Doppler Phase 2")
AddTextEntry("WEAPON_M9_DOPPLERP3", "M9 Bayonet Doppler Phase 3")
AddTextEntry("WEAPON_M9_DOPPLERP4", "M9 Bayonet Doppler Phase 4")
AddTextEntry("WEAPON_M9_DOPPLERRUBY", "M9 Bayonet Doppler Ruby")
AddTextEntry("WEAPON_M9_DOPPLERSAPPHIRE", "M9 Bayonet Doppler Sapphire")
AddTextEntry("WEAPON_M9_GDEMERALD", "M9 Bayonet Emerald")
AddTextEntry("WEAPON_M9_FADE", "M9 Bayonet Fade")
AddTextEntry("WEAPON_M9_FREEHAND", "M9 Bayonet Free Hand")
AddTextEntry("WEAPON_M9_GDP1", "M9 Bayonet Gamma Doppler Phase 1")
AddTextEntry("WEAPON_M9_GDP2", "M9 Bayonet Gamma Doppler Phase 2")
AddTextEntry("WEAPON_M9_GDP3", "M9 Bayonet Gamma Doppler Phase 3")
AddTextEntry("WEAPON_M9_GDP4", "M9 Bayonet Gamma Doppler Phase 4")
AddTextEntry("WEAPON_M9_LORE", "M9 Bayonet Lore")
AddTextEntry("WEAPON_M9_MARBLEFADE", "M9 Bayonet Marble Fade")
AddTextEntry("WEAPON_M9_SAFARIMESH", "M9 Bayonet Safari Mesh")
AddTextEntry("WEAPON_M9_SCORCHED", "M9 Bayonet Scorched")
AddTextEntry("WEAPON_M9_SLAUGTHER", "M9 Bayonet Slaugther")
AddTextEntry("WEAPON_M9_STAINED", "M9 Bayonet Stained")
AddTextEntry("WEAPON_M9_TIGERTOOTH", "M9 Bayonet Tiger Tooth")
AddTextEntry("WEAPON_M9_ULTRAVIOLET", "M9 Bayonet Ultra Violet")
AddTextEntry("WEAPON_M9_URBANMASKED", "M9 Bayonet Urban Masked")
AddTextEntry("WEAPON_BF_BLUESTEEL", "Butterfly Blue Steel")
AddTextEntry("WEAPON_BF_BOREALFOREST", "Butterfly Boreal Forest")
AddTextEntry("WEAPON_BF_CASEHARDENED", "Butterfly Case Hardened")
AddTextEntry("WEAPON_BF_CRIMSONWEB", "Butterfly Crimson Web")
AddTextEntry("WEAPON_BF_DAMASCUSSTEEL", "Butterfly Damascus Steel")
AddTextEntry("WEAPON_BF_DOPPLERBLACKPEARL", "Butterfly Doppler Black Pearl")
AddTextEntry("WEAPON_BF_DOPPLERPHASE1", "Butterfly Doppler Phase 1")
AddTextEntry("WEAPON_BF_DOPPLERPHASE2", "Butterfly Doppler Phase 2")
AddTextEntry("WEAPON_BF_DOPPLERPHASE3", "Butterfly Doppler Phase 3")
AddTextEntry("WEAPON_BF_DOPPLERPHASE4", "Butterfly Doppler Phase 4")
AddTextEntry("WEAPON_BF_DOPPLERRUBY", "Butterfly Doppler Ruby")
AddTextEntry("WEAPON_BF_DOPPLERSAPPHIRE", "Butterfly Doppler Sapphire")
AddTextEntry("WEAPON_BF_FADE", "Butterfly Fade")
AddTextEntry("WEAPON_BF_FOREST", "Butterfly Forest")
AddTextEntry("WEAPON_BF_NIGHT", "Butterfly Night")
AddTextEntry("WEAPON_BF_RUSTCOAT", "Butterfly Rust Coat")
AddTextEntry("WEAPON_BF_SAFARIMESH", "Butterfly Safari Mesh")
AddTextEntry("WEAPON_BF_SCORCHED", "Butterfly Scorched")
AddTextEntry("WEAPON_BF_SLAUGTHER", "Butterfly Slaugther")
AddTextEntry("WEAPON_BF_STAINED", "Butterfly Stained")
AddTextEntry("WEAPON_BF_TIGERTOOTH", "Butterfly Tiger Tooth")
AddTextEntry("WEAPON_BF_ULTRAVIOLET", "Butterfly Ultra Violet")
AddTextEntry("WEAPON_BF_URBANMASKED", "Butterfly Urban Masked")
AddTextEntry("WEAPON_KARAMBIT_AUTOTRONIC", "Karambit Autotronic")
AddTextEntry("WEAPON_KARAMBIT_BLACKLAMINATE", "Karambit Black Laminate")
AddTextEntry("WEAPON_KARAMBIT_BLUESTEEL", "Karambit Blue Steel")
AddTextEntry("WEAPON_KARAMBIT_BOREALFOREST", "Karambit Boreal Forest")
AddTextEntry("WEAPON_KARAMBIT_BRIGHTWATER", "Karambit Bright Water")
AddTextEntry("WEAPON_KARAMBIT_CASEHARDENED", "Karambit Case Hardened")
AddTextEntry("WEAPON_KARAMBIT_CRIMSONWEB", "Karambit Crimson Web")
AddTextEntry("WEAPON_KARAMBIT_DAMASCUSSTEEL", "Karambit Damascus Steel")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERBLACKPEARL", "Karambit Doppler BlackPearl")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERPHASE1", "Karambit Doppler Phase 1")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERPHASE2", "Karambit Doppler Phase 2")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERPHASE3", "Karambit Doppler Phase 3")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERPHASE4", "Karambit Doppler Phase 4")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERRUBY", "Karambit Doppler Ruby")
AddTextEntry("WEAPON_KARAMBIT_DOPPLERSAPPHIRE", "Karambit Doppler Sapphire")
AddTextEntry("WEAPON_KARAMBIT_FADE", "Karambit Fade")
AddTextEntry("WEAPON_KARAMBIT_FOREST", "Karambit Forest")
AddTextEntry("WEAPON_KARAMBIT_FREEHAND", "Karambit Free Hand")
AddTextEntry("WEAPON_KARAMBIT_GDEMERALD", "Karambit Gamma Doppler Emerald")
AddTextEntry("WEAPON_KARAMBIT_GDP1", "Karambit Gamma Doppler Phase 1")
AddTextEntry("WEAPON_KARAMBIT_GDP2", "Karambit Gamma Doppler Phase 2")
AddTextEntry("WEAPON_KARAMBIT_GDP3", "Karambit Gamma Doppler Phase 3")
AddTextEntry("WEAPON_KARAMBIT_GDP4", "Karambit Gamma Doppler Phase 4")
AddTextEntry("WEAPON_KARAMBIT_LORE", "Karambit Lore")
AddTextEntry("WEAPON_KARAMBIT_MARBLEFADE", "Karambit Marble Fade")
AddTextEntry("WEAPON_KARAMBIT_NIGHT", "Karambit Night")
AddTextEntry("WEAPON_KARAMBIT_RUSTCOAT", "Karambit Rust Coat")
AddTextEntry("WEAPON_KARAMBIT_SAFARIMESH", "Karambit Safari Mesh")
AddTextEntry("WEAPON_KARAMBIT_SCORCHED", "Karambit Scorched")
AddTextEntry("WEAPON_KARAMBIT_SLAUGTHER", "Karambit Slaugther")
AddTextEntry("WEAPON_KARAMBIT_STAINED", "Karambit Stained")
AddTextEntry("WEAPON_KARAMBIT_TIGERTOOTH", "Karambit Tiger Tooth")
AddTextEntry("WEAPON_KARAMBIT_ULTRAVIOLET", "Karambit Ultra Violet")
AddTextEntry("WEAPON_KARAMBIT_URBANMASKED", "Karambit Urban Masked")
